### ISSUE TITLE
Issue in runlmc/examples

### ISSUE THREAD

**Issue by essefi-ahlem** [vlad17/runlmc#5]
Hey @vlad17 

I am actually trying to run locally the examples' notebooks you've put in runlmc/examples. There I've encountered some issues in both notebooks that I will be detailing here :

**For the example.ipynb :** 

An error occurred when calling the function of InterpolatedLLGP 
the error was TypeError: 'numpy.float64' object cannot be interpreted as an integer
I still cannot get it why it is no longer accepting floats.

**For fx2007.ipynb** 

The function foreign_exchange_2007() is using the ix library which is now deprecated (and causing errors) in Python to do the slicing from a given data frame.
This ix function needs to be replaced (I tried with loc and iloc) and it is used twice in the file standard_tester.py (located in runlmc/benchmarks/benchlib/standard_tester.py) 

Hope that this will be solved soon.

**Comment by vlad17** [comment]
Thanks for flagging these issues. As I mentioned in our chat, I can only maintain this library in my spare time which is why I could only take a look at this issue this weekend.

In the future, to save time, please include [gists](https://gist.github.com/) of the full error message you're seeing. That would let me point out a fix that you could hopefully implement (and push back as a pull request) yourself in a shorter time frame.

Both of the issues you mentioned were quick fixes luckily. They all came from numpy/pandas updates to the api. Perhaps it'd be a wise idea to pin the libraries to a specific version...

Regardless, you were on the right track for fixing the `ix` to `loc/iloc` translation and the other issue was simply a cast needing to be added (numpy stopped accepting int-valued floats where it expected an int).
